### ISSUE TITLE
License

### ISSUE THREAD

**Issue by halkeye** [k0ka/EcoCalculator#9]
Is your intention that other people can use the code? fork it? suggest changes or run thier own copy?
As it stands right now I can't give you any help upgrading to 9.x because the non license is super restrictive.

Can you add a license, even if you want to keep it restrictive, just so its clear what your intentions are?

My vote is always MIT - https://tldrlegal.com/license/mit-license

**Comment by k0ka** [comment]
Hi.

Sure, you may use my code. I've added the MIT license.

**Comment by halkeye** [comment]
\o/

When i get things working at least basically, i'll make a PR, up to you if you want to accept it, i don't see this as a long term project for me
